name: MooseRound
favicon: null
layout_spectrum: 0.88847
typography_spectrum: 0.12566
title: MooseRound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b090a'
    - '#644d48'
    - '#699429'
    - '#aeb2bd'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
