name: MooseRound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12566
title: MooseRound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f336'
    - '#e9002f'
    - '#a1a29c'
    - '#2d2d2b'
    - '#f05c27'
  brandStrength: 0
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
purpose: []
