name: Moose round
favicon: null
layout_spectrum: 0.8293894263915718
typography_spectrum: 0.6622778854798526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.08648290252313018
  lightness: 0.26439616410061717
  saturation: 0.958150184713304
  rhythmicContrast: 0.42963739787228405
purpose: []
